---
title: "hw_1"
author: "Ilya Ershov"
date: "20 02 2018"
output: html_document
---

### 1.1
```{r}
library(tidyverse)
df <- read.csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/levantic/hw1_agreement/hw1_1_zilo_class.csv", encoding = 'UTF-8')
df1 %>%
  distinct(stimulus_source, translation_ru) %>%
  count(stimulus_source)
head(df1)
```
### 1.2
```{r}
library(irr)
df %>% 
  select(s_id, stimulus, translation_ru, stimulus_source, class) %>% 
  spread(key = s_id, value = class) ->
  zilo_classes_short
agree(zilo_classes_short[,-c(1:3)])
```
### 1.3
```{r}
zilo_classes_two <- zilo_classes_short[,c(7, 11)]
kappa2(zilo_classes_two)
```
### 1.4
```{r}
kappam.fleiss(zilo_classes_short[,-c(1:3)])
```
### 1.5
В данном исследовании подсчитывается, каким образом в зиловском диалекте андийского языка распределена исконная лексика и заимствования. Для подсчета меры согласия учитывались процент полного согласия (он равен 0.74), каппа Коэна (0.75) и каппа Фляйса (0.84). Данный результат показывает высокую степень согласованности между говорящими.
### 2.1
```{r}
df_2 <- read.csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/levantic/hw1_agreement/hw1_2_verbs.csv", encoding = 'UTF-8')
as_tibble(df_2) %>%
  summarise(n = n_distinct(SubjectCode)) -> df2
head(df2)
```
### 2.2
```{r}
as_tibble(df_2)%>%
  group_by(WordType, Gender)%>%
  summarise(mean = mean(GivenScore)) -> m
```
### 2.3
```{r}
as_tibble(df_2) %>% 
  select(SubjectCode, Stimulus, WordType, Prefix, GivenScore) %>% 
  spread(key = SubjectCode, value = GivenScore) ->
  df_2_short
df_2_short <- na.omit (df_2_short)
agree(df_2_short[,-c(1:3)])
```
### 2.4
```{r}
kappam.fleiss(df_2_short[,-c(1:3)])
```
### 2.5
```{r}
icc(df_2_short[,-c(1:3)], model = "twoway", type = "agreement")
```
### 2.6
```{r}
corr <- as.table(cor(df_2_short[,-c(1:3)], method = "kendall"))
result <- tibble(first=rownames(corr)[row(corr)[upper.tri(corr)]], 
              second=colnames(corr)[col(corr)[upper.tri(corr)]],
              correlation = corr[upper.tri(corr)])
tibble(max = max(result$correlation), min = min(result$correlation))
```
